[package]
name = "generator"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cbindgen = "0.29.2"

[dependencies]
oas3 = "0.20.1"
serde = "1.0.228"
serde_json = "1.0.145"
tera = "1.20.1"
ureq = "3.1.4"


[lib]
crate-type = ["staticlib"]

[lints.clippy]
